#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun 26 21:14:47 2025

@author: arash
"""
import torch.nn as nn
import torch
import numpy as np
import math
    


def assign_gt_to_voxels(assignments, c_voxels,
                        grid, gtl, voxel_size,
                        debug, ignore_class_id=-1):
    """
    Assigns ground truth objects to the 3D grid.

    Args:
        assignments: Tensor of shape [B, W, H, D]
        c_voxels: Tensor of shape [B, 18, 4]
        
        grid: Tensor of shape [W, H, D, 3] representing voxel centers (x, y, z)
        gtl: Shape: (B, 18, 14)
        
        Returns:
            assignments: Tensor of shape [B, W, H, D] with:
                - -1: background
                - >= 0: index of gtl object
                - -2: ignored (like tram)
            c_voxels:Tensor of shape [B, 18, 4]:
                for each object (dim=1) the i, j, k of the center of the voxel related to that object
                as well as its object ID is written
    """
   
    B, max_objects, _ = gtl.shape
    W, H, D = grid.shape[:3]
    device = grid.device
    
    for b in range(B):
        if gtl[b, 0, 13] == 0:
             # no object
             continue
        else:
            for obj_idx in range(max_objects):
                if int(gtl[b, obj_idx, 13]) == 1:
                    h, w, l = gtl[b, obj_idx, 0:3]
                    cx, cy, cz = gtl[b, obj_idx, 3:6]
                    cat = int(gtl[b, obj_idx, 12])
        
                    # if object is smaller than an edge of the voxel:
                    w = max(w, voxel_size[0])
                    h = max(h, voxel_size[1])
                    l = max(l, voxel_size[2])
        
                    # AABB
                    x_min, x_max = cx - w / 2, cx + w / 2
                    y_min, y_max = cy - h / 2, cy + h / 2
                    z_min, z_max = cz - l / 2, cz + l / 2
        
                    # mask voxels inside this object
                    xs, ys, zs = grid[..., 0], grid[..., 1], grid[..., 2]
                    inside = (xs >= x_min) & (xs <= x_max) & \
                             (ys >= y_min) & (ys <= y_max) & \
                             (zs >= z_min) & (zs <= z_max)
        
                    assert inside.sum() != 0
        
                    # assign voxel values
                    if cat == ignore_class_id:
                        assignments[b][inside] = -2
                    else:
                        assignments[b][inside] = obj_idx
        
                    # find voxel closest to GT center
                    voxel_coords = grid[inside]
                    dists = torch.norm(voxel_coords - gtl[b, obj_idx, 3:6].to(device), dim=1)
                    min_idx = torch.argmin(dists)
                    idx_flat = torch.nonzero(inside, as_tuple=False)[min_idx]
                    i, j, k = idx_flat.tolist()
                    c_voxels[b, obj_idx] = torch.tensor([i, j, k, obj_idx], device=device)

    return assignments, c_voxels

def aggregate_assignment(assignments):
    """
    *** Function generated by GPT
    
    Collapse [W, H, D] voxel assignments into [W, D] BEV map.
    Function to map the grid to a BEV grid with shape W, D and same values as assignment

    Rules:
    - If any object index (>= 0) is present in the pillar, choose one randomly.
    - Else if any ignored (-2) is present, choose -2.
    - Else set to -1 (background).
    
    assignments is a list were len(assignments) == batch_size
    """
    
    assignments_bev = []
    
    for ass in assignments:
        W, H, D = ass.shape
        bev = torch.full((W, D), -1, dtype=ass.dtype, device=ass.device)
    
        # Iterate over pillars (x,z)
        for x in range(W):
            for z in range(D):
                pillar = ass[x, :, z]
    
                obj_mask = pillar >= 0
                ign_mask = pillar == -2
    
                if obj_mask.any():
                    # pick one object randomly
                    candidates = pillar[obj_mask]
                    idx = torch.randint(0, len(candidates), (1,), device=ass.device)
                    bev[x, z] = candidates[idx]
                elif ign_mask.any():
                    bev[x, z] = -2
                else:
                    bev[x, z] = -1
        assignments_bev.append(bev)
        
    return assignments_bev

# Corrections made:
    # XXX: Objectness loss is corrected, considering no detection, removing gtl from method
    # XXX: classification is done now for all voxels belong to a detected object, done
    # XXX: center loss also is calculated for all voxels of an object, done
    # TODO: dropping must be corrected! done

class loss_bev(nn.Module):
    def __init__(self, cfg, grid, oob_mask_valid):
        super(loss_bev, self).__init__()
        self.cfg = cfg
        
        self.grid = grid
        assert self.grid.shape[-1] == 3, f"Expected grid[..., 3] for (x,y,z), got shape {grid.shape}"
        
        self.grid_bev = self._grid3d_to_grid2d()
        
        self.oob_mask_valid = oob_mask_valid
        # oob_mask_valid is:
        #    shape 100, 30, 70 and where the voxel is out of boundary of image --> False otherwise, True
        
        self.num_c = self.cfg.model.num_class
        self.loss_weights = self.cfg.loss.weight
        self.alpha = self.cfg.loss.alpha
        self.gamma = self.cfg.loss.gamma
        self.beta = self.cfg.loss.beta
        self.voxel_size = self.cfg.grid_unc
        self.lb = self.cfg.debug_loss  # local debug
        
    def _grid3d_to_grid2d(self):
        bev_grid = self.grid[:, 0, :, :][:, :, [0, 2]]
        # bev_grid will be 100, 70, 2
        return bev_grid
    
    def object_conf_loss(self, pred_obj_logits, voxel_assignments):
        """
        pred_obj_logits: [B, 1, W, D]
        voxel_assignments: a list of tensors (shape W*D) with lenght = B and -1=bg, -2=ignored, >=0=object
        """
        loss = []

        for b in range(self.B):
            target = (voxel_assignments[b] >= 0).float()
            valid = (voxel_assignments[b] != -2)
            pred = pred_obj_logits[b, 0][valid]
            tgt = target[valid]
            
            if pred.numel() == 0:
                continue  # skip this batch if no valid voxels
        
            # Focal BCE
            bce = nn.functional.binary_cross_entropy_with_logits(pred, tgt, reduction='none')
            pt = torch.exp(-bce)
            focal_loss = self.alpha * (1 - pt) ** self.gamma * bce
            loss.append(focal_loss.mean())
                
        # XXX: reduce mem overhead
        # del target, valid, pred, tgt
        
        if len(loss) == 0:
            return torch.tensor(0.0, device=pred_obj_logits.device, requires_grad=True)
        else:
            return torch.stack(loss).mean()

    def _drop_dets(self, assignments, init_c_voxels, init_gtl):
        """
        Drops ground truth objects that fall outside the camera view.
    
        Args:
            assignments: Tensor [B, W, H, D] with voxel→object indices
            init_c_voxels: Tensor [B, 18, 4] (i, j, k, obj_idx)
            init_gtl: Tensor [B, 18, 14] (object parameters)
    
        Returns:
            assignments: Updated tensor with dropped voxels set to -1
            c_voxels: Updated (B, 18, 4) tensor (invalid ones set to -1)
            gtl: Updated (B, 18, 14) tensor (dropped objects set to 0)
        """
        B, max_objects, _ = init_gtl.shape
        
        for b in range(B):
            # skip if this batch has no valid objects
            if init_gtl[b, :, 13].sum() == 0:
                continue

            vox = init_c_voxels[b]
            valid_mask = vox[:, 0] >= 0
        
        return assignments, init_c_voxels, init_gtl
    
    def classification_loss(self, pred_cls_logits, assignments, gtl):
        """
        pred_cls_logits: [B, num_classes, W, D]
        assignments: list of assignment space (W*D)
        """
        loss = []
        for b in range(self.B):
            if len(gtl[b]) == 0:
                continue
            else:
                valid_mask = (assignments[b] >= 0) & (assignments[b] != -2)  # only valid object voxels
                if valid_mask.sum() == 0:
                    continue
                
                indices = assignments[b][valid_mask]  # [N], contains GT indices
                class_targets = []
                
                for ids in indices:
                    gt_idx = ids.item()
                    target_cls = gtl[b][int(gt_idx)]['category']
                    if target_cls == -1:
                        class_targets.append(-100)  # ignore class
                    else:
                        class_targets.append(int(target_cls))
                        
                class_targets = torch.tensor(class_targets, device=pred_cls_logits.device)
                
                # Preds for valid voxels: [N, C]
                pred_voxels = pred_cls_logits[b].permute(1, 2, 0)[valid_mask]
                
                ce = nn.functional.cross_entropy(pred_voxels, class_targets, reduction='none', ignore_index=-100)
                pt = torch.exp(-ce)
                focal_loss = self.alpha * (1 - pt) ** self.gamma * ce
        
                loss.append(focal_loss.mean())
            
        # XXX: reduce mem overhead
        # del pred_voxels, class_targets, valid_mask
            
        if len(loss) == 0:
            return torch.tensor(0.0, device=pred_cls_logits.device, requires_grad=True)
        else:
            return torch.stack(loss).mean()
        
        
    def center_loss(self, pred_offsets, assignments, gtl, grid):
        """
        pred_offsets: [B, 2, W, D]
        grid: [W, D, 2]
        
        """
        # if assignments[0].device != oob_mask_valid.device:
        #     oob_mask_valid = oob_mask_valid.to(assignments[0].device)
        # TODO: check do we need again to use valid mask?
        
        loss = []
        for b in range(self.B):
            if len(gtl[b]) == 0:
                continue
            else:
                # Mask for voxels inside image boundaries and for objects
                # TODO: if we need val;id mask, must be added here to logic
                valid_mask = (assignments[b] >= 0) & (assignments[b] != -2)  # [W, D]
                if valid_mask.sum() == 0:
                    continue
            
                # Only valid voxels
                i, k = torch.nonzero(valid_mask, as_tuple=True)  # each is a (N,) tensor
            
                # Finding gt_idx of valid voxels
                gt_indices = assignments[b][i, k] # is a (N,) tensor
            
                # Centers of valid voxels
                voxel_centers = grid[i, k, :]  # (N, 2)
            
                # Predicted offsets
                pred_offsets_valid = pred_offsets[b][:, i, k].permute(1, 0)  # (N, 2)
            
                # Predicted centers
                pred_obj_centers = voxel_centers.to(pred_offsets.device) + pred_offsets_valid  # (N, 2)
            
                # Corresponding gt centers for each valid voxel
                gt_centers = torch.stack([
                    gtl[b][idx]['bbox_bev'][2:4].to(pred_offsets.device) for idx in gt_indices], dim=0)  # (N, 2)
            
                # Compute L1 loss per voxel
                l1 = nn.functional.smooth_l1_loss(pred_obj_centers, gt_centers, reduction='none', beta = self.beta)  # (N, 2)
                l1 = l1.mean(dim=1)  # (N,)
            
                loss.append(l1)
        
        # del l1, gt_centers, voxel_centers, valid_mask
        
        if len(loss) == 0:
            return torch.tensor(0.0, device=pred_offsets.device, requires_grad=True)
        else:
            return torch.cat(loss).mean()
        
        
    def dimension_loss(self, pred_dims, center_voxels, gtl):
        """
        pred_dims: [B, 2, W, D]
        """
        
        loss = []
        
        for b in range(self.B):
            if len(gtl[b]) == 0:
                continue
            else:
                for (i, j, k, gt_idx) in center_voxels[b]:
                    pred = pred_dims[b, :, i, k]
                    gt = gtl[b][gt_idx]['bbox_bev'][0:2].to(pred.device)
                    loss.append(nn.functional.l1_loss(pred, gt))
                    
        if len(loss) == 0:
            return torch.tensor(0.0, device=pred_dims.device, requires_grad=True)
        else:
            return torch.stack(loss).mean()
        
    def yaw_loss(self, pred_yaw, center_voxels, gtl):
        """
        pred_yaw: [B, 1, W, D]
        """
        loss = []
        
        for b in range(self.B):
            if len(gtl[b]) == 0:
                continue
            else:
                for (i, j, k, gt_idx) in center_voxels[b]:
                    pred = pred_yaw[b, 0, i, k]
                    gt = gtl[b][gt_idx]['bbox_bev'][4].to(pred.device)
                    
                    # minimal angle difference (in radians) in range [-π, π]
                    diff = (pred - gt + math.pi) % (2 * math.pi) - math.pi
                    
                    loss.append(nn.functional.smooth_l1_loss(diff, torch.tensor(0.0, device=pred_yaw.device)))

        if len(loss) == 0:
            return torch.tensor(0.0, device=pred_yaw.device, requires_grad=True)
        else:
            return torch.stack(loss).mean()

    def forward(self, prediction, init_gtl):
        """
        prediction is:
            pred[:num_class] = class probabilities,
            pred[num_class] = objecness score,
            pred[num_class + 1 : num_class + 3] = offsets from voxel center,
            pred[num_class + 3 : num_class + 5] = object dimensions,
            pred[-1] = object box yaw angle
            *** Prediction comes like [n, out_ch, w_res, d_res]
            
        init_gtl is is a Tensor:
            Shape: (B, 18, 14) where:
                B is batch size
                18 is maximum object per instance
                14 = 7 for 3d box, 5 for bev vox, 1 for category, and 1 for valid obj
            3d box order is: h, w, l, cx, cy, cz, yaw
            box bev order is w, l, cx, cz, yaw
            object class (zero to num_classes-1 and -1 for not important objects)

        """
        
        assert len(prediction) == len(init_gtl), "Values are not all equal, batch size mismatch with prediction"
        assert prediction.shape == (len(init_gtl), 10, self.grid.shape[0], self.grid.shape[2]), \
            f"Prediction has a wrong shape, expected shape is: [n, out_ch, w_res, h_res, d_res], received: {prediction.shape}"
            
        assert init_gtl.shape == (len(prediction), 18, 14), \
            f"Prediction has a wrong shape, expected shape is: [n, out_ch, w_res, h_res, d_res], received: {prediction.shape}"
        
        self.B = len(prediction)
        if self.B == 0:
            device = prediction.device
            return {k: torch.tensor(0.0, device=device) for k in ['obj_conf', 'cls_loss', 'center_loss', 'dim_loss', 'yaw_angle_loss', 'total']}
        
        self.loss = {}
        
        
        init_assignments = torch.full((self.B, self.grid.shape[0], self.grid.shape[1], self.grid.shape[2]),
                                      fill_value=-1, dtype=torch.long, device=self.grid.device)
        
        init_c_voxels = torch.full((self.B, 18, 4),
                                      fill_value=-1, dtype=torch.long, device=self.grid.device)
        
        init_assignments, init_c_voxels = assign_gt_to_voxels(init_assignments, init_c_voxels,
                                                              self.grid, init_gtl, self.voxel_size, self.lb)
        
        
        # Removing out of the bound detections from ground truth
        assignments, c_voxels, gtl = self._drop_dets(init_assignments, init_c_voxels, init_gtl)
        
        assert len(assignments) == len(c_voxels) == self.B, "Batch size mismatch between assignment, voxel centers, and self.B (post-drop)"
        if len(c_voxels) > 0:
                assert len(init_c_voxels[0]) >= len(c_voxels[0]), "After drop, must be equal or less detections!"
                if self.lb:
                    print(f" ==>  detection number of 1st droped sample:  {len(c_voxels[0])}")
                    
        assignments_bev = aggregate_assignment(assignments)
        del assignments
        
        # Objectness loss
        self.loss['obj_conf'] = self.object_conf_loss(prediction[:, self.num_c:self.num_c+1], assignments_bev)

        # class loss (might be useful if focal loss is used)
        self.loss['cls_loss'] = self.classification_loss(prediction[:, 0:self.num_c], assignments_bev, gtl)
        
        # bbox center loss
        self.loss['center_loss'] = self.center_loss(prediction[:, self.num_c+1 : self.num_c+3],
                                       assignments_bev, gtl, self.grid_bev)

        # bbox dim loss
        self.loss['dim_loss'] = self.dimension_loss(prediction[:, self.num_c+3: self.num_c+5],
                                       c_voxels, gtl)
        
        # yaw angle loss
        # Any normalization on each term? No, just weights
        assert prediction[:, self.num_c+5:].shape[1] == 1
        self.loss['yaw_angle_loss'] = self.yaw_loss(prediction[:, self.num_c+5:], c_voxels, gtl)

        # Total loss: Sum of all loss considering their importance based on self.loss_weights
        self.loss['total'] = self.loss_weights[0]*self.loss['obj_conf'] + \
                                self.loss_weights[1]*self.loss['cls_loss'] + \
                                self.loss_weights[2]*self.loss['center_loss'] + \
                                self.loss_weights[3]*self.loss['dim_loss'] + \
                                self.loss_weights[4]*self.loss['yaw_angle_loss']
                                
        if self.lb:
            print("-------------------- loss forward ended--------------------")
            
        return self.loss
    
